# Generated by Django 5.0.6 on 2024-09-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept',
            new_name='location',
        ),
    ]
